### ISSUE TITLE
Could not initialize class jcuda.nvrtc.JNvrtc...

### ISSUE THREAD

**Issue by okdzhimiev** [jcuda/jcuda-imagej-example#1]
```
jcuda-imagej-example/target -> Fiji.app/plugins
└──  JCuda_ImageJ_Example_Plugin.jar 
```
```
jcuda-imagej-example/target/dependency -> Fiji.app/jars
├── ij-1.52a.jar
├── jcuda-0.9.0d.jar
├── jcuda-natives-0.9.0d-linux-x86_64.jar
└── tools-1.4.2.jar
```
When running the plugin getting the following error:
```
(Fiji Is Just) ImageJ 2.0.0-rc-68/1.52e; Java 1.8.0_172 [64-bit]; Linux 4.4.0-134-generic; 148MB of 5999MB (2%)
 
java.lang.NoClassDefFoundError: Could not initialize class jcuda.nvrtc.JNvrtc
	at JCuda_ImageJ_Example_Plugin.setup(JCuda_ImageJ_Example_Plugin.java:129)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:48)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by okdzhimiev** [comment]
Fixed after updating deps in pom.xml (and rebuilding).
```
    <dependencies>
        <dependency>
            <groupId>net.imagej</groupId>
            <artifactId>ij</artifactId>
            <version>1.52e</version>
        </dependency>
        <dependency>
            <groupId>org.jcuda</groupId>
            <artifactId>jcuda</artifactId>
            <version>0.9.2</version>
        </dependency>
    </dependencies>
```

**Comment by jcuda** [comment]
I'll just reopen this until I updated the POM in the repo as well (otherwise, it will get lost)
